# Generated by Django 4.2.6 on 2024-09-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_type', models.CharField(choices=[('PC', 'program core'), ('PE', 'program elective'), ('UC', 'university core'), ('UE', 'university elective'), ('FLP', 'foreign language basket'), ('STS', 'softskills')], default='PC', max_length=3)),
                ('embedded_status', models.CharField(choices=[('ETL', 'Embedded Theory and Lab'), ('TH', 'Theory only'), ('LO', 'Lab only')], default='ETL', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=100)),
                ('theory_slots', models.JSONField(blank=True, default=list)),
                ('lab_slots', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='base.course')),
            ],
        ),
    ]
