# Generated by Django 4.2.6 on 2024-09-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('PC', 'program core'), ('PE', 'program elective'), ('UC', 'university core'), ('UE', 'university elective'), ('FLP', 'foreign language basket'), ('STS', 'softskills')], default='PC', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='embedded_status',
            field=models.CharField(blank=True, choices=[('ETL', 'Embedded Theory and Lab'), ('TH', 'Theory only'), ('LO', 'Lab only')], default='ETL', max_length=3),
        ),
    ]
