# Generated by Django 4.2.6 on 2024-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_course_course_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='professor',
            new_name='prof',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
