# Generated by Django 4.2.6 on 2024-09-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_course_title_slot_unique_course_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='lab_slots',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='theory_slots',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
